### ISSUE TITLE
How does this identify unauthorized ssl certificate

### ISSUE THREAD

**Issue by pavankomarina** [ProtonMail/ct-monitor#1]
How does this app identifies unauthorised SSL certificates . As far as i see , it only calls google transparency API and fetches all the certificates and store it in the database.

**Comment by mazen160** [comment]
Hi @pavankomarina 

Thanks for your message.

ct-monitor is utilizing Google API for certificate transparency logs in order to identify new certificates.

Please check: https://transparencyreport.google.com/https/certificates?hl=en

**Comment by pavankomarina** [comment]
Yeah i checked that it is using google-api . But my question is how does this identify whether that certificate is legitimate or not . While fetching certificates for a particular domain , how can we exactly identify malicious certificates amongst those.

**Comment by mazen160** [comment]
We can't actually identify forged certificates automatically correctly, but you can check manually if it's issued by your organization or not.
